# Generated by Django 5.2.6 on 2025-09-09 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('pros', models.JSONField(default=list, help_text='List of strings for career pros.')),
                ('cons', models.JSONField(default=list, help_text='List of strings for career cons.')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('academic_level', models.CharField(choices=[('10th', 'Class 10th'), ('12th', 'Class 12th')], max_length=10)),
                ('stream', models.CharField(help_text='e.g., Engineering, Medicine', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=255)),
                ('backreason', models.TextField(blank=True, null=True)),
                ('scores', models.JSONField(default=dict, help_text='A JSON object mapping career slugs to score values.')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='careerapp.question')),
            ],
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('academic_level', models.CharField(choices=[('10th', 'Class 10th'), ('12th', 'Class 12th')], max_length=10)),
                ('stream', models.CharField(max_length=50)),
                ('results_data', models.JSONField(default=dict, help_text='Raw data of quiz scores per career.')),
                ('recommendations', models.JSONField(default=list, help_text='Final top N recommendations as a list of dicts.')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CareerCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('saved_attempts', models.ManyToManyField(blank=True, to='careerapp.quizattempt')),
            ],
        ),
    ]
