# Generated by Django 4.2 on 2025-09-12 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0003_auto_20250911_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('required_skills', models.JSONField(default=list)),
                ('interest_keywords', models.JSONField(default=list)),
                ('degree_requirements', models.JSONField(default=list)),
                ('salary_range', models.CharField(blank=True, max_length=50)),
                ('growth_prospects', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very_high', 'Very High')], max_length=20)),
                ('work_environment', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CareerRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField()),
                ('reasoning', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.career')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-match_score'],
                'unique_together': {('user', 'career')},
            },
        ),
    ]
